### ISSUE TITLE
CONTRIBUTION

### ISSUE THREAD

**Issue by swathi-469** [SamarthMR/AI-ML-for-Newborn-Babies-in-Healthcare#1]
I would like to add contribution guidelines for beginners in open source in a form of contribution.md file ..please assign this to me

**Comment by prathimacode-hub** [comment]
Hey, welcome to the repo. Ofcourse you can do, follow the issue template given [here](https://github.com/SamarthMR/AI-ML-for-Newborn-Babies-in-Healthcare/blob/main/.github/ISSUE_TEMPLATE/feature_request.md) and get this isssue assigned to you. Just edit the above comment and do the changes according to the task you are choosing. That's it. @swathi-469

**Comment by prathimacode-hub** [comment]
Sorry to say, there was no follow up from you. Can you revert back with the changes? @swathi-469

**Comment by swathi-469** [comment]
No mam I ma working on it

**Comment by prathimacode-hub** [comment]
It's not about working or not. You can't work on issue without getting the issue assigned. That's against the rule. First get it assigned. To get it assigned, follow the issue template given in README file of the project.. So that i could assign the issue to you. @swathi-469

**Comment by swathi-469** [comment]
I am just confused ... You have given a template so I need to edit the template and answer the questions raised and after that I need to propose or else .. I need to copy the content in the template and edit and add it in the comment .. please correct me ...

**Comment by prathimacode-hub** [comment]
You just add the template and edit it according to your issue needs and fill it up appropriately. That's it. This is to just know you and the issue. Are you an devincept participant? @swathi-469

**Comment by swathi-469** [comment]
So for this I need to fork Is it ?

**Comment by prathimacode-hub** [comment]
Press ... dots beside your comment, there is an edit option. You can edit the comment. @swathi-469

**Comment by swathi-469** [comment]
Ohh kk

**Comment by prathimacode-hub** [comment]
Once I see your template i shall assign it to you
@swathi-469

**Comment by swathi-469** [comment]
I have requested can you check

**Comment by swathi-469** [comment]
Sir if possible can we have a Google meet please

**Comment by swathi-469** [comment]
A small meet sir please

**Comment by prathimacode-hub** [comment]
If you need help let us know, instead of stuggling all alone

**Comment by prathimacode-hub** [comment]
You can ask me if you need guidance, i shall help you out. Let me know. @swathi-469

**Comment by prathimacode-hub** [comment]
If you want to ping sir specifically, you can through the slack channel. @swathi-469

**Comment by swathi-469** [comment]
Yeah sir , I gone through the README but still I am unable to get it ..  if
there is any video it would be really helpful for me.

**Comment by prathimacode-hub** [comment]
Ok, you wanted google meet right? @swathi-469

**Comment by swathi-469** [comment]
Yes sir

**Comment by prathimacode-hub** [comment]
I'm not sir, ok send me with the link of google meet i shall show you the process without an audio by sharing up the screen. You just follow the steps guided. And you will be good to go. @swathi-469

**Comment by swathi-469** [comment]
sorry mam
Here's the link :
https://meet.google.com/die-hxdx-dso

**Comment by prathimacode-hub** [comment]
Project Title :  Here the project title
Name : Your full name
Label : Feature Request

Define You:

- [x] DevIncept Participant 
- [ ] Contributor


 Yes or No

**Is your feature request related to a problem? Please describe.**

 Here describe the issue you had taken and what you have to do

**Describe the solution you'd like...**

 Here give your idea, your approach and how would you like to proceed to make this work

**Describe alternatives you've considered?**

 Here you add any other alternatives you would think of if it didn't work as expected

**Approach to be followed (optional):**

 How would you like to proceed and make this happen into successful contribution

**Additional context**

 Here you can add any resources you would refer while working on this issue or any thing you want to convey regarding the feature request (issue).

**Comment by swathi-469** [comment]
Title: CONTRIBUTION_GUIDELINES
about: Guidelines for the beginners in open source
name: Swathi A
label: Feature Request

Define You:

- [x] DevIncept Participant 
- [ ] Contributor


 Yes

**Is your feature request related to a problem? Please describe.**

Open Source Contribution involves contributing to the development or improvement of open-source software. In order to provide better guidelines for beginners, step-by-step guidelines are provided to contribute in open-source through Github.

**Describe the solution you'd like...**

In order to understand the command lines and their purpose, a set of instructions is provided with screenshots, resources to be downloaded before contribution, and so on.

**Describe alternatives you've considered?**

The command lines  can be given in the cell with the help of Jupiter

**Approach to be followed (optional):**

Sample screenshots can be added to make it more clear, resource link can be attached.

**Additional context**

Resouces links to be downloaded before starting contribution are included.

**Comment by prathimacode-hub** [comment]
Issue assigned. @swathi-469

**Comment by swathi-469** [comment]
Thank you mam
