### ISSUE TITLE
PAIN [vid 3-4]

### ISSUE THREAD

**Issue by SamarthMR** [SamarthMR/AI-ML-for-Newborn-Babies-in-Healthcare#5]
Work on extracting 50 RGB images of the baby's facial expressions from each video. Later, convert the 50 RGB images to gray scale images. So, you will be extracting totally 100 images from each video. You have been assigned with 2 videos i.e., video [3-4] in the dataset present under '**Pain**' folder which contains 49 videos.

Dataset Link: https://livemissouristate-my.sharepoint.com/:f:/g/personal/nyc10040_missouristate_edu/Ev2GCLuXRK1DsgbeiRGRywkBBzLLqRH-OKaMi3rFHuM3iA?e=Zm3XcU
Password: 3maF'N+53xKj{

Click on iCOPEvid folder inside the link and download only the video datasets to your desktops that are assigned to you here and start working.

**Comment by iharshidas** [comment]
Define You:

✅ DevIncept Participant
Contributor
Is your feature request related to a problem? Please describe.
It is related to the problem mentioned as per the project subject.

Describe the solution you'd like...
To extract 50 images each from the two videos and convert them to grayscale. There will be 200 images in total, 100 in RGB while the same 100 in grayscale as well.
After that facial expressions of the babies will be examined using OpenCV in Python. Accordingly, the pictures will be sorted into 3 different folders - No-Mild Pain, Moderate Pain and Severe Pain.

**Comment by iharshidas** [comment]
Could I get this issue assigned to myself.

**Comment by prathimacode-hub** [comment]
Are you sure you want to work on it? @iharshidas

**Comment by iharshidas** [comment]
Yes

**Comment by prathimacode-hub** [comment]
Ok, issue assigned. @iharshidas
